version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: image-processing-api-dev
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
      - ./pytest.ini:/app/pytest.ini
      - ./app/static/uploaded:/app/app/static/uploaded
      - ./app/static/edited:/app/app/static/edited
      - ./app/static/detected:/app/app/static/detected
      - ./logs:/app/logs
    environment:
      - DEBUG=True
      - LOG_LEVEL=DEBUG
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    stdin_open: true
    tty: true

